import CheckoutForm from "@/components/checkout/CheckoutForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};
const CheckoutPage = () => {
  return <CheckoutForm />;
};
export default CheckoutPage;
