import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import "./globals.css";
import { languages } from "./i18n/setting";
import Menu from "@/components/menu/Menu";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children, params: { lng } }: A) {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <Header language={lng}></Header>
        <Menu language={undefined} />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
