import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { NextUIProvider } from "@nextui-org/react";
import { Inter } from "next/font/google";
import "./globals.scss";
import { languages } from "./i18n/setting";
import { dir } from "i18next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children, params: { lng } }: A) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <NextUIProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </NextUIProvider>
      </body>
    </html>
  );
}
