import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

export default async function Layout({ children }: A) {
  return <>{children}</>;
}
