import type { Metadata } from "next";
import Footer from "@/components/footer/Footer";
import React from "react";

export const metadata: Metadata = {
  title: "Shopper",
  description: "Generated by create next app",
};

export default async function Layout({ children, params: { locale } }: A) {
  return (
    <>
      {children}
      <Footer></Footer>
    </>
  );
}
