import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import SearchBox from "@/components/header/SearchBox";
import React from "react";
import Breadcumb from "@/components/header/Breadcrumb";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Shopper",
  description: "Generated by create next app",
};

export default function Layout({ children, params: { locale } }: A) {
  return (
    <>
      <Header language={locale}></Header>
      <Breadcumb language={locale} />
      <SearchBox className="block md:hidden px-2" />
      <Toaster />
      <main className="container mx-auto px-2 md:px-0">{children}</main>
      <Footer></Footer>
    </>
  );
}
