import type { Metadata } from "next";
import React from "react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function Layout({ children }: A) {
  return (
    <>
      <nav className="container w-full px-2 bg-white/90 sticky top-0 z-40 backdrop-blur-sm border-b flex-none transition-colors duration-500  ">
        <Link href="/" className="mr-4">
          <h1 className="font-bold text-xl text-inherit">LOGO</h1>
        </Link>
      </nav>
      {children}
    </>
  );
}
